MYS and GDYS hooks were updated.

diff --git a/roles/gitolite/templates/gdys-post-receive.sh.j2 b/roles/gitolite/templates/gdys-post-receive.sh.j2
--- a/roles/gitolite/templates/gdys-post-receive.sh.j2
+++ b/roles/gitolite/templates/gdys-post-receive.sh.j2
@@ -1,4 +1,10 @@
 #!/bin/bash
 
-touch ~/gdys.txt
-echo "gdys repo specific test." >> ~/gdys.txt
+/usr/bin/ssh -ntt -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ahtapotops@localhost -i /home/gitolite/.ssh/gdyshook
+
+EXIT=$?
+
+if [ "$EXIT" -ne 0 ]
+then
+	/usr/bin/logger -p local5.crit "GDSY HOOK SSH Connection Failed!"
+fi
diff --git a/roles/gitolite/templates/mys-post-receive.sh.j2 b/roles/gitolite/templates/mys-post-receive.sh.j2
--- a/roles/gitolite/templates/mys-post-receive.sh.j2
+++ b/roles/gitolite/templates/mys-post-receive.sh.j2
@@ -1,4 +1,10 @@
 #!/bin/bash
 
-touch ~/mys.txt
-echo "mys repo specific test." >> ~/mys.txt
+/usr/bin/ssh -ntt -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ahtapotops@localhost -i /home/gitolite/.ssh/myshook
+
+EXIT=$?
+
+if [ "$EXIT" -ne 0 ]
+then
+	/usr/bin/logger -p local5.crit "MSY HOOK SSH Connection Failed!"
+fi
